# Generated by Django 4.1.2 on 2022-11-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nmap',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.basemodel')),
                ('name', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=200)),
                ('xml_name', models.CharField(max_length=100)),
                ('xml_file', models.FileField(upload_to='nmap/xml/')),
                ('scan_type', models.CharField(max_length=100)),
            ],
            bases=('services.basemodel',),
        ),
    ]
