# Generated by Django 4.1.2 on 2022-12-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nmap',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.basemodel')),
                ('name', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=200)),
                ('ports', models.CharField(blank=True, max_length=200, null=True)),
                ('xml_name', models.CharField(max_length=100)),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='nmap/xml/')),
                ('arguments', models.CharField(blank=True, max_length=100, null=True)),
                ('output', models.TextField(blank=True, null=True)),
            ],
            bases=('services.basemodel',),
        ),
    ]
