# Generated by Django 4.1.2 on 2022-11-13 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nmap',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.basemodel')),
                ('name', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=200)),
                ('xml_name', models.CharField(max_length=100)),
                ('xml_file', models.FileField(upload_to='nmap/xml/')),
                ('scan_type', models.CharField(max_length=100)),
                ('command_line', models.CharField(max_length=300)),
                ('scan_method', models.CharField(blank=True, max_length=100, null=True)),
                ('services', models.CharField(blank=True, max_length=100, null=True)),
                ('scan_protocol', models.CharField(blank=True, max_length=100, null=True)),
                ('timestr', models.CharField(blank=True, max_length=100, null=True)),
                ('elapsed', models.CharField(blank=True, max_length=100, null=True)),
                ('uphosts', models.CharField(blank=True, max_length=100, null=True)),
                ('downhosts', models.CharField(blank=True, max_length=100, null=True)),
                ('totalhosts', models.CharField(blank=True, max_length=100, null=True)),
                ('ipv4', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_state', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_product', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_version', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_extrainfo', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_conf', models.CharField(blank=True, max_length=100, null=True)),
                ('tcp_port_cpe', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('services.basemodel',),
        ),
    ]
