# Generated by Django 4.1.2 on 2022-11-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmap',
            name='command_line',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
